import "../styles/globals.css";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  <Head>
    <title>AR3D</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="/favicon.ico" />
  </Head>;
  return <Component {...pageProps} />;
}

export default MyApp;
